#define IDI_NOTIFICATIONICON 101
#define IDC_NOTIFICATIONICON 102
#define IDI_NOTIFICATIONICON_CONNECTED 103
#define IDS_APP_TITLE 104

#define TOOLTIP_CONNECTED 105
#define TOOLTIP_DISCONNECTED 106

#define IDC_CONTEXTMENU 201

#define FTDI_CONNECTED 301
#define FTDI_DISCONNECTED 302

// Menuitems
#define IDM_EXIT 401
